coisa = input('Digite alguma coisa: ')
print('O tipo primitivo de {} é ', type(coisa))
print('{} tem espaços? '.format(coisa), coisa.isspace() )
print('{} é um número? '.format(coisa), coisa.isnumeric() )
print('{} é alfabético? '.format(coisa), coisa.isalpha() )
print('{} é alfanúmerico? '.format(coisa), coisa.isalnum() )
print('{} está em maiúscula? '.format(coisa), coisa.isupper() )
print('{} está em minúscula? '.format(coisa), coisa.islower() )
print('{} está capitalizada? '.format(coisa), coisa.istitle() )
